### PR TITLE
add pregenerated man page in mdoc

### PR DESCRIPTION
**Pull request by epsilon-0**
looks better and drops dependency on scdoc

Signed-off-by: Aisha Tammy <floss@bsd.ac>

### CODE REVIEW

**Comment by epsilon-0** [comment]
Here is how it looks like from scdoc - https://i.imgur.com/HgCz6TX.png
Here is with the newer man page - https://i.imgur.com/KnPKVfo.png

**Comment by fluix-dev** [comment]
I'm going to guess that `scdoc` is used because it's much easier to edit manpages in such format instead of the native format. I personally doubt that this dependency will be removed, however with regards to:

> looks better

It _should_ be possible to make the `scdoc` generated one look identical. Also, without knowing anything about the standards of man pages, at least _some_ changes don't match many of the man pages that I have. For example, the `NAME` section doesn't have the program name bolded (see `man man`), yet in the new version it does.

**Comment by emersion** [comment]
Sorry, I like scdoc.

**Comment by epsilon-0** [comment]
> Sorry, I like scdoc.

No worries.

**Pull request closed without merging**
