### PR TITLE
fish completions: add missing option

### PR DESCRIPTION
**Pull request by ammgws**
Forgot to add this in the last PR.
﻿

### CODE REVIEW

**Comment by ammgws** [comment]
By the way, can fish-completions be set to true in meson_options like it is in `sway`?

**Comment by emersion** [comment]
No, I prefer this to be opt-in.

**Comment by ammgws** [comment]
OK, I might upstream them to fish itself then otherwise they will never get installed when installing from a package manager (or at least `grim-git` on AUR which is what I'm using)

**Comment by emersion** [comment]
Distribution packages can enable it (`meson … -Dfish-completions=true`).

**Comment by ammgws** [comment]
Would you be willing to enable it for the AUR package? (Seeing as you're the maintainer)

**Comment by emersion** [comment]
Ahah, forgot I was the maintainer. Sure.

Because of a fish bug, this won't install the files at the correct location though. https://github.com/fish-shell/fish-shell/pull/6778 fixes this.

**Comment by emersion** [comment]
As a side note, 05927ea82b2839763d294f9de08ed5fe4f5c7633 and 7a557737249d4ec36b656f96758c6dde4bf04acd fix two issues I encountered while installing fish completions.

**Pull request merged**
